# This is the docker-compose file to run Medplum's required background serivces
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
services:
#  node:
#   restart: always
#    build: 
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:5000'
#      - '8081:8103'
#    networks:
#      - demo
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - '5430:5432'
    networks:
      - demo  
  redis:
    image: redis:6
    restart: always
    command: redis-server --requirepass medplum
    ports:
      - '6379:6379'
    networks:
      - demo
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
   # depends_on:
   #   - node
    networks:
      - demo
networks:
  demo:
    driver: bridge
